# Generated by Django 2.2.3 on 2019-11-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191113_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='good_info',
            name='good_num',
            field=models.IntegerField(default=20, verbose_name='商品库存'),
        ),
        migrations.AddField(
            model_name='good_info',
            name='is_onsale',
            field=models.BooleanField(default=True, verbose_name='是否在销售'),
        ),
    ]
